name: instrumented tests

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Verify Emulator version
        run: /Users/runner/Library/Android/sdk/emulator/emulator -version

      - name: Run instrumented tests
        run: ./gradlew pixel4api30DebugAndroidTest -Pandroid.sdk.channel=3 --info
