name: instrumented tests

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level:
          - 24
          - 26
          - 29
          - 30
          - 31

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.22.0
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          disable-animations: true
          profile: Nexus 6
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          script: ./gradlew connectedCheck --stacktrace

#     UTP disables due to some issues with GitHub Actions
#     For more information: https://issuetracker.google.com/issues/193118030
#      - name: Run instrumented tests
#        run: ./gradlew alkaaDevicesGroupDebugAndroidTest -Pandroid.sdk.channel=3
